title: Tungsten Moon
description: Home of the Tungsten Moon game
theme: just-the-docs

url: https://tungstenmoon.comm

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
